### ISSUE TITLE
Update honkers-launcher

### ISSUE THREAD

**Issue by Sw3d15h-F1s4** [ezKEa/aagl-gtk-on-nix#105]
Hi! I'm pretty new to NixOS, so I apologize if I'm missing something obvious. I greatly appreciate the hard work you've done to make installing honkers-railway-launcher so simple, and it works really well.

However, I also have tried installing honkers-launcher (for HI3), and it doesn't work. I'm experiencing the same issue as:
https://github.com/an-anime-team/honkers-launcher/issues/38

The version of honkers-launcher installed is 1.6.1 according to the about screen, and I noticed there's a 1.6.2 version released. I'm not sure if this issue fixes what the problem was, but the issue was closed so I'd assume so. I also saw you made a commit around the same not too long ago, so I tried to update to the latest version. I'm using a nix flake to manage my system, and my flake.lock says I'm using the latest commit of aagl-gtk-on-nix. I've followed the flake installation instructions provided in the README. I've set it to follow unstable nixpkgs, as that's what I use for the rest of my system. However, doing `nixos-rebuild switch` after a `nix flake update` doesn't install the 1.6.2 version of honkers-launcher. 

Am I missing something? Again I'm new to NixOS, so maybe I don't know exactly how to update packages hosted outside of nixpkgs. I've tried to look at ezkea.cachix.org to see if I could figure out which version is hosted, but I have no clue how to work that site.

Sorry for the inconvenience, and thank you in advance.

**Comment by LudovicoPiero** [comment]
You can test it out with `nix build github:LudovicoPiero/aagl-gtk-on-nix/bump-packages#honkers-launcher`.

**Comment by Sw3d15h-F1s4** [comment]
honkers-launcher works perfectly now! Thank you!
