### ISSUE TITLE
Update workflow broken

### ISSUE THREAD

**Issue by musjj** [ezKEa/aagl-gtk-on-nix#156]
It looks like the update action has been broken for the last couple of weeks:

https://github.com/ezKEa/aagl-gtk-on-nix/actions/runs/11872190984

**Comment by ezKEa** [comment]
I don't think so. This is what it's supposed to do when there is not an update available

**Comment by musjj** [comment]
That's strange because I'm getting a cache miss recently (it starts building locally).
