### ISSUE TITLE
Any chance of including the Honkai launcher?

### ISSUE THREAD

**Issue by ghost** [ezKEa/aagl-gtk-on-nix#22]
Any chance of including the [Honkai launcher](https://github.com/an-anime-team/honkers-launcher) as well? Would be appreciated!

**Comment by ezKEa** [comment]
Hi! Thanks for the opening an issue. I don't play Honkai Impact myself, so I don't have any interest in maintaining a package for this launcher. However, it is worth noting that honkers-launcher is essentially a fork of anime-game-launcher (as far as I know it has exactly the same dependencies as AAGL). In fact, you can probably even be able to convince Nix to build and run it using the right invocation of override and overrideAttrs on this nix package. Alternatively, if you would like to properly implement a package for honkers-launcher (based on my AAGL package) and would be willing to maintain it, I would gladly accept a PR. Short of that, I sadly have no plans to add it. Thank you for understanding!

**Comment by ezKEa** [comment]
Reopened because, upon trying, overriding aagl package in this repo to get a honkers-launcher package isn't actually as simple as I suspected it would be. I might add the honkers launcher at some point later.
