### ISSUE TITLE
Failed to login in an anime game: 数据异常

### ISSUE THREAD

**Issue by YisuiDenghua** [ezKEa/aagl-gtk-on-nix#29]
Device: Lenovo Legion Y9000X IAH7 (2022)
CPU: 12th Gen Intel Core i7-12700H × 20
GPU1: Intel Graphics (ADL GT2)
GPU2: NVIDIA GeForce RTX 3060 Mobile
System: Linux x86_64, NixOS 23.05.20230509.4487c14, 
Kernel: Linux 6.3.1-zen1

Game Version: 3.6.0, Chinese version.
Wine version: Wine-GE-Proton 8.4
DXVK version: 2.1

Error type: "数据异常，请重新登录游戏。"
![genshinfail](https://github.com/ezKEa/aagl-gtk-on-nix/assets/102890144/cc3ce65a-016a-4ace-9e4e-c46e1b7911d1)

**Comment by ezKEa** [comment]
Hi! Are you playing with the xLua patch enabled? If so, try disabling it. This is known to happen sometimes in the CN version with the xLua patch enabled. You can try re-enabling it in a few days and it might work (I think it's some server side check that's failing for whatever reason but I'm not sure).

**Comment by YisuiDenghua** [comment]
Solved by running `cd ~/.local/share/anime-game-launcher/YuanShen && bash ../patch/360/patch_revert.sh && bash ../patch/360/patch.sh`

**Comment by ezKEa** [comment]
Glad the fix was something simple!
