### ISSUE TITLE
Upstreaming to Nixpkgs

### ISSUE THREAD

**Issue by CutestNekoAqua** [ezKEa/aagl-gtk-on-nix#68]
Hi, can / do we want to upstream this to nixpkgs?

**Comment by ezKEa** [comment]
Hi. I've gotten this question a few times, so now is probably a good time to state why I've refrained from upstreaming these modules and packages into nixpkgs:
1) Merging into nixpkgs would make the speed at which I can make changes and update the packages significantly slower by virtue of the review process. Thus far I've been able to keep the launcher packages up to date within at least 1 day of updates being released (in fact, I've build a non-trivial amount of CI infrastructure in this repo for this specifically).
2) I don't want to bring any unneeded attention to the bypasses the launcher use, at the request of the launcher and patch developers. Even though GI now works without a patch, and `anime-game-launcher` could arguably be merged into Nixpkgs without much problem, this could change at any time if the game developers decide they want to finally switch to Tencent's AntiCheatExpert (as HI3 did). In this situation, the AAGL launcher and HI3/HSR patch would likely be updated to allow us to keep playing, but the launcher's presence in nixpkgs would essentially be advertising the bypass. I want to avoid this.

For these reasons, I don't plan to ever upstream this repo into nixpkgs. Thank you for understanding.
