### ISSUE TITLE
Build Error: 'builtins.storePath' not allowed in pure evaluation mode

### ISSUE THREAD

**Issue by LovingMelody** [ezKEa/aagl-gtk-on-nix#75]
While attempting to build with commit facc119d22404a3fb2572dfa6efbc6ac31bf9746 I receive the error `'builtins.storePath' is not allowed in pure evaluation mode.` but this issue is not present with commit 0c9d93bdb311f7948f9fb0e98d869316d78eec12

**Comment by LovingMelody** [comment]
This repo is being used as a flake input.
```nix
  inputs = {
    aagl.inputs.nixpkgs.follows = "nixpkgs";
    aagl.url = "github:ezKEa/aagl-gtk-on-nix/0c9d93bdb311f7948f9fb0e98d869316d78eec12";
```
but commit 2e0c4a4667f9aac0246843d2d8ee530856d4b679 fixed it. Thanks!

**Comment by ezKEa** [comment]
I realized why this is happening. I'll fix this later.

**Comment by ezKEa** [comment]
This should be fixed now @LovingMelody. Let me if if you have any issues with the latest commit.

**Comment by ezKEa** [comment]
> @ezKEa this is still occurring for me.

Are you using this repo as a flake input? Can I see a config?

**Comment by xusiai** [comment]
@ezKEa I'm using home-manager. I was able to build aagl earlier this week and the issue has arisen at some point since then. 

```
{pkgs, ...}: let
  aagl-gtk-on-nix = import (builtins.fetchTarball {
    url = "https://github.com/ezKEa/aagl-gtk-on-nix/archive/main.tar.gz";
    sha256 = "19sdy32lqx9g5b07ja3sdn5cdwsiclbdxnk0mhjbxfr39xsjw0ja";
  });
in {
  home.packages = with pkgs; [
    aagl-gtk-on-nix.anime-game-launcher
    aagl-gtk-on-nix.anime-borb-launcher
    aagl-gtk-on-nix.honkers-railway-launcher
    aagl-gtk-on-nix.honkers-launcher
  ];
}
```
